version: '3'

services:

  schulcloud-client:
    image: schulcloud-client:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      BACKEND_URL: http://schulcloud-server:3030/
    ports:
      - 3100:3100
      # - 5858:5858
    external_links:
      - schulcloud-server:server
    volumes:
      - .:/app
    command: npm run watch

  schulcloud-client-gulp:
      image: schulcloud-client:latest
      build:
        context: .
        dockerfile: Dockerfile
      environment:
        NODE_ENV: development
      volumes:
        - .:/app
      # command: /opt/node_modules/.bin/gulp watch
      command: /opt/node_modules/.bin/gulp

networks:
  default:
    external:
      name: schulcloudserver_schulcloud-server-network